Update slack.yml

diff --git a/.github/workflows/slack.yml b/.github/workflows/slack.yml
--- a/.github/workflows/slack.yml
+++ b/.github/workflows/slack.yml
@@ -33,9 +33,14 @@ jobs:
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/actions/artifacts \
             | jq -r '.artifacts[0].id')
-          
+
+          if [ -z "$artifact_id" ]; then
+            echo "Artifact ID not found"
+            exit 1
+          fi
+
           # Construct the artifact download URL
-          download_url="https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id/zip?access_token=${{ secrets.TOKEN_GITHUB }}"
+          download_url="https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id/zip"
           
           echo "artifact_download_url=$download_url" >> $GITHUB_ENV
 
